services:
  backend:
    container_name: onboard_backend
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - onboard_net
    command: sh -c "sleep 5 && ./main"

  database:
    container_name: onboard_db
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./onboard-data:/var/lib/postgresql/data:rw
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - onboard_net

networks:
  onboard_net:
