apiVersion: apps/v1
kind: Deployment
metadata:
  name: onboard-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onboard
  template:
    metadata:
      labels:
        app: onboard
    spec:
      containers:
        - name: onboard
          image: nsahil992/onboard:v1
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
