apiVersion: v1
kind: Service
metadata:
  name: onboard-service
spec:
  selector:
    app: onboard
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30200
      protocol: TCP