apiVersion: v1
kind: PersistentVolume
metadata:
  name: onboard-postgres-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /Users/Sahil/Desktop/OnBoard/onboard-data